import type { Badge } from './types';

export const USER_AVATAR =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCa5i2t-7cSOefy4PhGgP2hUXUQC71gqzMcT6z8mZxviDV4J-AdiiPanZOvDC2oLyk1f2lAyY62ui-sgDxyEbQ26hRf662qDx6WixfCwLKwQTXkYXtWYa9xGTfOFoNeMk08PZjMaWSdJ6LQlVAEZs-YZjx4r05ZOBkpXRsJKWy6VCwyKRZ4RvbX1wxIjW58keE0358ASAXM8ovS2qZ62ci-6ELbMc0OdWGR03MONHw3ouMhtugElL4DrVhxOJBR2Dj9JR3jeO6crP0';

export const LEAF_DETAIL =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBIT-4BGCSwERRikgjWKCJ_uIdI-3DguFuImRhDs8C85NzW5Kfuj35DbijUnhQw45IUi9Yc5tuEJGYK42KUU7z96MVBuPh8pUOsAhuiVheP4Veolo8HvLgBOs7DlWhK8ltSneV2pdBu-7n99JXu0_FYWx9yYDZb2LuRZXMGg6V8xcory1Gh0DKbwLi5LtQSgkwf6iPzP4TNum7UL5_Fcc9TfW_jcImguKwFuqHJGgbH_6TmM5RRa7AOgjNoEGJ9f2XML_pbuKQBNcg';

export const SUCCULENT_MACRO =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAVHNT5XBa5dL4E8c39McIbtG82tAUJ2wF6bw0AtXEzJVc4jwilxZDO_GXaCfhWHEdJeXRdAii2st9YazAj42DLtRxn7I8CZfZzten7Y-2ZMkkDQ2iN1dhV_cHiCfc73-N89B10KQaq8WXCCT9fqwPj2POF5qzSgiDsJUpHbEviYMjddWN8MpFbVtHLtkz0zdZMIvcNE9tpev0X_qXBQIXEeDyD-QaxGpLpEKMa0l8b4OV984oBYWMzaE5mNUyi3wT6W_sJ_TwFI1M';

export const ACHIEVEMENT_BADGES: Badge[] = [
  {
    id: 'top-gardener',
    title: 'Top Gardener',
    description: 'Care for plants for 30 days straight.',
    icon: 'trophy',
    earned: true,
    type: 'featured',
    level: 'Legendary',
    progress: 30,
    goal: 30,
    result: '30-day care streak',
  },
  {
    id: 'water-expert',
    title: 'Water Expert',
    description: 'Finish watering quests before your plants droop.',
    icon: 'waves',
    earned: true,
    type: 'standard',
    level: 'Level 5',
    progress: 50,
    goal: 50,
    result: '50 waterings completed',
  },
  {
    id: 'seedling',
    title: 'Seedling',
    description: 'Add your first plant and complete its starter care.',
    icon: 'leaf',
    earned: true,
    type: 'standard',
    level: 'Level 1',
    progress: 1,
    goal: 1,
    result: 'First plant rooted',
  },
  {
    id: 'sun-chaser',
    title: 'Sun Chaser',
    description: 'Log bright indirect light checks.',
    icon: 'sun',
    earned: true,
    type: 'standard',
    level: 'Level 3',
    progress: 12,
    goal: 12,
    result: '12 light checks',
  },
  {
    id: 'streak-keeper',
    title: 'Streak Keeper',
    description: 'Complete any care quest seven days in a row.',
    icon: 'flame',
    earned: true,
    type: 'standard',
    level: 'Level 2',
    progress: 7,
    goal: 7,
    result: '7-day quest streak',
  },
  {
    id: 'scan-scholar',
    title: 'Scan Scholar',
    description: 'Scan plants to build your care library.',
    icon: 'scan',
    earned: false,
    type: 'standard',
    level: 'Level 2',
    progress: 6,
    goal: 10,
    result: '6 of 10 plant scans',
  },
  {
    id: 'pruning-pro',
    title: 'Pruning Pro',
    description: 'Complete tidy-up tasks without skipping.',
    icon: 'scissors',
    earned: false,
    type: 'standard',
    level: 'Level 2',
    progress: 4,
    goal: 8,
    result: '4 of 8 tidy-ups',
  },
  {
    id: 'greenhouse-guardian',
    title: 'Greenhouse Guardian',
    description: 'Finish every daily quest for a full week.',
    icon: 'shield',
    earned: false,
    type: 'standard',
    level: 'Level 4',
    progress: 5,
    goal: 7,
    result: '5 of 7 perfect days',
  },
  {
    id: 'rare-bloom',
    title: 'Rare Bloom',
    description: 'Unlock after every badge in this set reaches gold.',
    icon: 'lock',
    earned: false,
    type: 'locked',
    level: 'Locked',
    progress: 0,
    goal: 1,
    result: 'Hidden challenge',
  },
];
